name: Deploy Docs Site to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/deploy-docs.yml"
      - "website/**/*"

jobs:
  deploy:
    defaults:
      run:
        working-directory: website
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./build
