name: Deploy Docs Site to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/deploy-docs.yml"
      - "website/**"

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # defaults:
    #   run:
    #     working-directory: website
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install dependencies
        run: | 
          cd website
          yarn install --frozen-lockfile
      - name: Build website
        run: |
          cd website
          yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./website/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
      - run: ls -a
