name: Deploy Docs Site

on:
  push:
    branches:
      - master
    paths:
      - "cloud-docs/**/*"

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint

  Deploy:
    needs: [Lint]
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy
        uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: cloud-docs
          git-user: ${{ github.actor }}
          git-password: ${{ github.token }}
          deployment-branch: gh-pages
