name: Hello World

on:
  push:
    branches:
      - master

jobs:
  hello:
    name: Say hello!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: Enable yarn
        run: corepack enable
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Hello
        run: echo "Hello World!"
        
